select * from HR.JOBS;
select * from HR.countries;
select * from HR.JOBS;
select * from HR.JOBS;
select * from HR.employees;
CREATE TABLE JDemployees AS SELECT * FROM HR.employees;
SHOW USER;
SELECT USER FROM DUAL;
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_TAB_PRIVS;
SHOW tables;
SELECT owner, table_name FROM ALL_TABLES ORDER BY owner, table_name;
SELECT * FROM jdemployees;